### ISSUE TITLE
Not possible to define the sources without showing a helm buffer

### ISSUE THREAD

**Issue by jkp** [emacs-helm/helm-ls-git#34]
Hi

The current implementation seems to require a call to `(helm-ls-git-ls)` to actually define the sources - for some setups this isn't always desirable.  Would it be possible to provide a way to allow them to be defined on require?

**Comment by jeaye** [comment]
This is an issue for me, since I want to source `helm-source-ls-git` along with others without calling `helm-ls-git-ls` directly.

I'm currently using:
```lisp
(define-key evil-normal-state-map
            (kbd "C-p")
            (lambda ()
              (interactive)
              (helm :sources '(helm-source-ls-git
                               helm-source-locate)
                    :buffer "*helm-find-files*")))
```

As @jkp mentioned, this only works after having called `helm-ls-git-ls` once.

**Comment by thierryvolpiatto** [comment]
jeaye <notifications@github.com> writes:

> This is an issue for me, since I want to source helm-source-ls-git along with others without calling helm-ls-git-ls directly.
>
> I'm currently using:
>
> (define-key evil-normal-state-map
>             (kbd "C-p")
>             (lambda ()
>               (interactive)
>               (helm :sources '(helm-source-ls-git
>                                helm-source-locate)
>                     :buffer "*helm-find-files*")))
>
> As @jkp mentioned, this only works after having called helm-ls-git-ls once.

Because the sources are nil and are initialized at run time.
You have to create the sources yourself.

BTW It is strange using these two sources together.

NOTE: Don't ask me setting up the sources in source-code file, all
sources in helm are going to be nil in a near future...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
